packages/react-mla/src/components/properties/LinkProperties.tsx, packages/react-mla/src/components/ribbon/tab/LayoutTabPanel.tsx, packages/react-mla/src/utils/date.ts, packages/react-mla/src/utils/vis-data-utils.ts
Correct issue if date is invalid when importing
Corrected styling and dates
=> fix: correct spelling, styling and dates

.github/workflows/lint.yml, .github/workflows/ssfscorecard.yml, .github/workflows/workflow.yml, README.md
This PR fixes broken links and badges in the README page.
=> Cleanup after release

apps/web/package.json, package.json, packages/config-tailwind/package.json, packages/react-mla/package.json, packages/webcomponent-mla/package.json, pnpm-lock.yaml
Updates tailwindcss and vite to latest version
=> chore: Update packages according to audit

apps/desktop/src/index.html
Fixes title and config in electron app
=> fix: correct title in electron app

.github/dependabot.yml, .github/workflows/commit.yml, .github/workflows/license.yml, .github/workflows/lint.yml, .github/workflows/lintpubliccode.yml, .github/workflows/release-package.yml
Harden workflows by pinning actions and adding default security permissions
=> chore: harden workflow by pinning actions

.github/workflows/build.yml, .github/workflows/workflow.yml
CI workflow should build the project
=> fix: add build step to ci workflow

.github/workflows/release-package.yml
Add slsa provenance to the release workflow (first try)
=> fix: add slsa

.github/dependabot.yml
Add directories to group configuration
=> fix: add directories to configuration

.github/workflows/commit.yml, .github/workflows/license.yml, .github/workflows/lint.yml, .github/workflows/lintpubliccode.yml
fix: Optimize the build process
=> fix: Optimize workflow

.github/workflows/create-release.yml, .github/workflows/deploy-release.yml
=> fix: new release workflow

.github/workflows/create-release-draft.yml, .github/workflows/create-release.yml, .github/workflows/deploy-release.yml, CHANGELOG.md
=> fix: Add release workflow

SECURITY.md
fix: Add security.md file to project
=> fix: Add security-md file to project

.github/workflows/fast_forward.yml
Fix: Perform fetch before checkout
=> fix: Fix error in fast-forward workflow

.github/workflows/fast_forward.yml
Fix: Add pull to workflow to be able to merge later
=> fix: Add pull to workflow

renovate.json
=> fix: fix lockfile maintenance

.github/workflows/create-release-draft.yml, .github/workflows/deploy-release.yml, .github/workflows/lint.yml
fix: Remove top level permission if not needed
=> fix: Remove security-event top level permissions

.github/workflows/deploy-release.yml
=> fix: Add read permission

.github/workflows/deploy-release.yml
fix: Add write permissions to job
=> fix: Add write permissions

renovate.json
fix: Add automerge for minor and patches
=> fix: Add automerge to minor and patches

README.md
[Please include a summary of the change and which issue is fixed or added.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes #(issue)](fix: Add OSS Best Practices Badge to readme)
=> fix: Add OSS Best Practices Badge to readme

README.md
=> fix: Set style on badge

.github/workflows/create-release-draft.yml
=> Fix: create release as bot

CHANGELOG.md, package.json, packages/react-mla/package.json, packages/webcomponent-mla/package.json
=> chore: Release v1.1.2

.github/workflows/deploy-release.yml, renovate.json
fix: remove pinning from slsa because of issue
=> fix: remove pinning from slsa because of issue

CHANGELOG.md, package.json, packages/react-mla/package.json, packages/webcomponent-mla/package.json
=> chore: Release v1.1.3

.github/workflows/test.yml, .github/workflows/workflow.yml, README.md
Adds a test badge to the readme
=> fix: add test badge

.github/workflows/test.yml
=> fix: rename test names for clairty

README.md
=> fix: Add name to test badge

CODEOWNERS, renovate.json
Enable vuln handling so that Renovate can create PRs for security issues
=> feat: Enable renovate vuln handling

.lefthook/commit-msg/commitlint.sh, commitlint.config.js, lefthook.yml, package.json, pnpm-lock.yaml
=> feat(dev): add git hooks

CHANGELOG.md, packages/react-mla/package.json, packages/react-mla/src/components/common/AppShortcuts.tsx, packages/react-mla/src/components/common/ContextMenu.tsx, packages/react-mla/src/components/common/Footer.tsx, packages/react-mla/src/components/ribbon/tab/AnalysisTabPanel.tsx, packages/react-mla/src/components/ribbon/tab/MapTabPanel.tsx, packages/react-mla/src/components/ribbon/tab/StyleTabPanel.tsx, packages/react-mla/src/components/ribbon/toolbox/CreateToolbox.tsx, packages/react-mla/src/components/ribbon/toolbox/GraphToolbox.tsx, packages/react-mla/src/components/ribbon/toolbox/SearchToolbox.tsx, packages/react-mla/src/components/tools/ExploreTool.tsx, packages/react-mla/src/store/internal-actions.ts, packages/react-mla/src/store/main-store.ts, packages/react-mla/src/store/search-state.ts, pnpm-lock.yaml
=> refactor: update zustand to v5

CHANGELOG.md, package.json, packages/react-mla/package.json, packages/webcomponent-mla/package.json
- Update zustand to v5
- fix: Use property value instead of view value for rules
=> chore: Release v1.1.4

packages/config-tailwind/tailwind.config.ts, packages/config-typescript/base.json, packages/react-mla/.gitignore, packages/react-mla/package.json, packages/react-mla/src/MLA.scss, packages/react-mla/src/MLA.test.tsx, packages/react-mla/src/MLA.tsx, packages/react-mla/src/services/configurationService.ts, packages/react-mla/tsconfig.compilerOptions.json, packages/react-mla/tsconfig.json, pnpm-lock.yaml
Better use of sans as default font
=> fix: use sans as default font the tailwind way

.github/workflows/deploy-demo-app.yml, apps/web/package.json, pnpm-lock.yaml
feat: add workflow for deploying demo app
=> feat: add workflow for deploying demo app

.github/workflows/deploy-demo-app.yml
fix: add ability to run workflow manualy
=> fix: add ability to run workflow manualy

.github/workflows/deploy-demo-app.yml, apps/web/index.html, apps/web/package.json, apps/web/public/config/default.json, apps/web/public/config/firewall.json, apps/web/vite.config.ts, package.json, pnpm-lock.yaml
feat: deploy demo app using workflow
=> feat: deploy demo app using workflow

.github/workflows/deploy-demo-app.yml
fix: move permission to job level
=> fix: move permissions to job level

README.md
feat: add demo link to readme page
=> Add demo link to readme file

renovate.json
fix: ignore major node version updates
=> fix: ignore major node version updates

renovate.json
fix: ignor major versions of packge @types/node
=> fix: ignore @types/node major version

CHANGELOG.md, package.json, packages/react-mla/package.json, packages/webcomponent-mla/package.json
=> chore: Release v1.1.5
